### ISSUE TITLE
** BUILD FAILED **

### ISSUE THREAD

**Issue by ghost** [RJVB/OS-X-SAT-SMART-Driver#1]
SDK for 10.6?

$ xcodebuild -configuration Release
=== BUILD NATIVE TARGET SATSMARTDriver OF PROJECT SATSMARTDriver WITH CONFIGURATION Release ===
Check dependencies
error: There is no SDK with the name or path '/Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/macosx10.6'

*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)

**Comment by RJVB** [comment]
Yes, I build with the 10.6 SDK (I'm running 10.6.8).
When I execute `xcodebuild -configuration Release` all goes well and I don't see any reference to a (SDK) search path below the project directory.

Have you tried opening the project in Xcode and build from there? If you're running a more recent Xcode version that might be a required step to convert the project ...

**Comment by ghost** [comment]
Sorry, this is probably basic stuff, but still beyond my knowledge at this point. I am using Xcode 4.4 and the 10.6 SDK is not included. It's a major hassle to download the last version of Xcode 4.1 which has the 10.6 SDK and then remove the SDK and add symlinks or something… ?

Opening up the project in Xcode 4.4 gives me the same error as on the command line.

Thank you for your reply.  

## 

John Prokos
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by RJVB** [comment]
What if you select a more recent SDK for the project, in Xcode?

I'm sorry I can't help you with obtaining the 10.6 SDK for your Xcode version, as I said I'm running 10.6.8 and not ready to update the OS. I'm surprised (but not that much) that the SDK is not available anymore although I guess that there must be another means. Have you asked around on a Mac tech-savvy forum like Ars Technica?

If you're asking me whether it's a major hassle to download Xcode 4.1 - I don't know, never tried it. An Apple Developer account is free, and if you can download the dmg from developer.apple.com the installer should take you through the process. I'm guessing that people who upgraded from 4.1 will still have the 10.6 SDK - which BTW is a separate directory in /Developer/SDKs so you might also be able to extract it with a tool like Pacifist.

**Comment by ghost** [comment]
René,

I found my old backup of Xcode 4.1 and moved the 10.6 SDK into Xcode 4.4. It's recognized by Xcode 4.4 now but I still get this error when building.

error: There is no SDK with the name or path '/Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/macosx10.6'

Why is it looking for the SDK in the project folder? Any suggestions?

John  

## 

John Prokos
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by ghost** [comment]
René,

I found my old backup of Xcode 4.1 and moved the 10.6 SDK into Xcode 4.4. It's recognized by Xcode 4.4 now but I still get this error when building.

error: There is no SDK with the name or path '/Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/macosx10.6'

Why is it looking for the SDK in the project folder? Any suggestions?

John  

## 

John Prokos
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by RJVB** [comment]
I guess you relaunched Xcode for it to recognise the 10.6 SDK? Try to see if a complete clean of the project resolves the path issue, or if not, re-converting the original project or if that fails too, what happens when you create a new, simple (Hello World) project linking against that SDK. My project is not in any way configured to look for SDKs in the project directory, but I cannot tell of course what happened when your Xcode converted my project bundle ...

Since you like terminal work, you could also open the files inside the project bundle directory to see if they contain a hardcoded path for the SDK. But that shouldn't be necessary.

**Comment by ghost** [comment]
Hi,  

OK it started to build using 10.6 SDK but we ran into another issue:

Build target SATSMARTDriver

CompileC build/SATSMARTDriver.build/Debug/SATSMARTDriver.build/Objects-normal/x86_64/IOSATDriver.o IOSATDriver.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler

```
cd /Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver


setenv LANG en_US.US-ASCII


/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch x86_64 -fmessage-length=0 -nostdinc -fno-builtin -Wno-trigraphs -fno-exceptions -fno-rtti -msoft-float -O0 -fno-common -mkernel -Wno-missing-field-initializers -Wno-missing-prototypes -Wreturn-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wformat -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DDEBUG=1 -DKERNEL -DKERNEL_PRIVATE -DDRIVER_PRIVATE -DAPPLE -DNeXT -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -fapple-kext -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -mmacosx-version-min=10.8 -g -Wno-sign-conversion -iquote /Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/build/SATSMARTDriver.build/Debug/SATSMARTDriver.build/SATSMARTDriver-generated-files.hmap -I/Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/build/SATSMARTDriver.build/Debug/SATSMARTDriver.build/SATSMARTDriver-own-target-headers.hmap -I/Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/build/SATSMARTDriver.build/Debug/SATSMARTDriver.build/SATSMARTDriver-all-target-headers.hmap -iquote /Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/build/SATSMARTDriver.build/Debug/SATSMARTDriver.build/SATSMARTDriver-project-headers.hmap -I/Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/build/Debug/include -I/Developer/SDKs/MacOSX10.6.sdk/System/Library/Frameworks/IOKit.framework/Versions/A/Headers -I/System/Library/Frameworks/Kernel.framework/PrivateHeaders -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/Kernel.framework/Headers -I/Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/build/SATSMARTDriver.build/Debug/SATSMARTDriver.build/DerivedSources/x86_64 -I/Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/build/SATSMARTDriver.build/Debug/SATSMARTDriver.build/DerivedSources -F/Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/build/Debug -MMD -MT dependencies -MF /Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/build/SATSMARTDriver.build/Debug/SATSMARTDriver.build/Objects-normal/x86_64/IOSATDriver.d --serialize-diagnostics /Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/build/SATSMARTDriver.build/Debug/SATSMARTDriver.build/Objects-normal/x86_64/IOSATDriver.dia -c /Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/IOSATDriver.cpp -o /Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/build/SATSMARTDriver.build/Debug/SATSMARTDriver.build/Objects-normal/x86_64/IOSATDriver.o
```

In file included from /Users/JP/Downloads/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/IOSATDriver.cpp:18:

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/Kernel.framework/Headers/IOKit/scsi/IOSCSIPeripheralDeviceNub.h:54:10: fatal error: 'IOKit/IOSyncer.h' file not found

#include <IOKit/IOSyncer.h>

```
     ^
```

1 error generated.

## 

John Prokos
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by RJVB** [comment]
Did you see that last line? It tells you it is including header files from the 10.8 SDK. That's not what should be happening if Xcode really recognised the 10.6 SDK and accepted you using it. Either Xcode got confused OR something is wrong with your IOkit headers.
Where did you copy the 10.6 SDK? I hope you put it in
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk
that is, next to the 10.8 (and 10.7) SDK?!

BTW, if you open the Info/Settings window for the SatSMARTDriver and SatSMARTLib projects and scroll to the header search paths, you'll see the entry /Developer/SDKs/MacOSX10.6.sdk/System/Library/Frameworks/IOKit.framework/Versions/A/Headers
Supposing you installed your SDK in the directory above, you'll have to modify that entry to
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk/System/Library/Frameworks/IOKit.framework/Versions/A/Headers

Surely you must have seen that my version of this driver is based on someone else's code - someone who has been maintaining the code more actively than I. Unless you have a very specific reason to use my version, I'd suggest you rather try his, as he may be more likely to help you with post-10.6 specific problems!

**Comment by ghost** [comment]
Sorry,  

Thanks for getting me this far. :)  

## 

John Prokos
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by RJVB** [comment]
I modified the header search path specification so that it no longer references a specific SDK but rather the system's framework (/System/Library/Frameworks/IOKit.framework/Versions/A/Headers). This should be much more portable.

**Comment by paulbeard** [comment]
I've tried yours and the other you refer to as being more regularly maintained and still hit the same issue. Must be something on my end.

**Comment by RJVB** [comment]
Have you tried the version I just pushed?

**Comment by paulbeard** [comment]
On Jul 1, 2013, at 4:24 PM, René Bertin notifications@github.com wrote:

> Have you tried the version I just pushed?

I'm new at some of this, so I wasn't aware there were new commits. Just installed github to help me with that. 

So I get further now: 

/Users/paul/src/OS-X-SAT-SMART-Driver-RJVB/SATSMARTDriver/IOSATBusCommand.cpp:35:10: fatal error: 'IOKit/IOSyncer.h' file not found
#include <IOKit/IOSyncer.h>

I don't have that in the 10.8 SDK, only in the 10.7. Not sure what's up with that. 

## 

Paul Beard

This space intentionally left blank.

**Comment by RJVB** [comment]
If you have it in the 10.7 SDK you can always build for that - or else what happens when you comment out the include statement? Maybe the IOSyncer class is defined elsewhere on 10.8 ?

I'm trying to prepare an XCode4 project to help the transition, but I'm a bit stuck on warnings apparently unsupported by clang that 1) I didn't add to the project and 2) I cannot remove. Hate to say it, but the interface of XCode4 under 10.6 is worse than MSVC's!

**Comment by paulbeard** [comment]
On Jul 2, 2013, at 3:40 AM, René Bertin notifications@github.com wrote:

> If you have it in the 10.7 SDK you can always build for that - or else what happens when you comment out the include statement? Maybe the IOSyncer class is defined elsewhere on 10.8 ?
> 
> I'm trying to prepare an XCode4 project to help the transition, but I'm a bit stuck on warnings apparently unsupported by clang that 1) I didn't add to the project and 2) I cannot remove. Hate to say it, but the interface of XCode4 under 10.6 is worse than MSVC's!

I've given up on this for now.  Had to return the enclosure I was using to its usual duties. This was using a disk that was audibly failing, something I couldn't hear when it was in the belly of an iMac. I wanted to see if smartctl still picked up the bad sectors or what it could tell me.
